[tool.poetry]
name = "poetry-objectdetection"
version = "0.1.0"
description = ""
authors = ["Tim Germann <tim_germann@bluewin.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
